---
name: debug and test vars

on:
    workflow_dispatch:
    push:
        branches:
            - preprod

jobs:
    test:
        runs-on: preprod
    
        steps:
            - run: echo $COWSAY_MESSAGE > /var/www/html/cowsay.txt
              env:
                COWSAY_MESSAGE: ${{ vars.COWSAY_MESSAGE }}
            - run: cat /var/www/html/cowsay.txt
            - run: |
                echo "secret: $SECURE_MSG" > /var/www/html/secure.txt
              env:
                SECURE_MSG: ${{ secrets.SECURE_MSG }}
            - run: cat /var/www/html/secure.txt